# Generated by Django 3.1.4 on 2021-02-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20210220_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemsbasket', related_query_name='itemsbasket', to='Orders.basket', verbose_name='basket'),
        ),
    ]
