# Generated by Django 3.1.7 on 2021-03-13 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20210222_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='color',
            field=models.CharField(default=0, max_length=25, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, verbose_name='size'),
            preserve_default=False,
        ),
    ]
