# Generated by Django 3.1.4 on 2021-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmeta',
            name='value',
            field=models.CharField(max_length=50, verbose_name='value'),
        ),
    ]
